module.exports = {
  apps: [
    {
      name: "vignet-web",
      script: "npm",
      args: "run start",
      cwd: __dirname + "/..",
      env: { NODE_ENV: "production" },
      max_memory_restart: "1G",
      instances: 1,
      autorestart: true,
    },
    {
      name: "vignet-worker",
      script: "npm",
      args: "run worker",
      cwd: __dirname + "/..",
      env: { NODE_ENV: "production" },
      max_memory_restart: "512M",
      instances: 1,
      autorestart: true,
    },
    {
      name: "vignet-whatsapp-bridge",
      script: "npm",
      args: "run start",
      cwd: __dirname + "/../mini-services/whatsapp-bridge",
      env: {
        NODE_ENV: "production",
        WHATSAPP_BRIDGE_PORT: "3040",
        NEXT_JS_BASE_URL: "http://localhost:3003",
        WHATSAPP_BRIDGE_SECRET: process.env.WHATSAPP_BRIDGE_SECRET || "",
        LOG_LEVEL: "info",
      },
      max_memory_restart: "512M",
      instances: 1,
      autorestart: true,
    },
  ],
};
