#!/usr/bin/env bash
# ============================================================================
#  Vignet — راه‌اندازی یک‌باره‌ی whatsapp-bridge
#
#  این اسکریپت را فقط یک‌بار بعد از اولین deploy اجرا کنید. کار می‌کند:
#    1. تولید یک secret تصادفی بلند (با openssl)
#    2. ساخت mini-services/whatsapp-bridge/.env با همان secret
#    3. اضافه کردن WHATSAPP_BRIDGE_URL + WHATSAPP_BRIDGE_SECRET به .env اصلی
#       پروژه Next.js (اگر هنوز وجود ندارند)
#    4. نصب وابستگی‌های bridge با bun (یا npm به‌عنوان fallback)
#    5. ثبت bridge در pm2 (با ecosystem.config.js آپدیت‌شده)
#    6. ذخیره‌ی pm2 برای استارت خودکار بعد از ریبوت
#
#  بعد از این اسکریپت، برای آپدیت‌های بعدی فقط کافیست deploy/deploy.sh
#  را اجرا کنید — bridge هم به‌صورت خودکار reload می‌شود.
# ============================================================================
set -euo pipefail

# به ریشه‌ی پروژه برو
cd "$(dirname "$0")/.."
ROOT="$(pwd)"

BRIDGE_DIR="$ROOT/mini-services/whatsapp-bridge"
BRIDGE_PORT="${WHATSAPP_BRIDGE_PORT:-3040}"

# domain یا آدرسی که Next.js روی آن در دسترس است. به‌صورت پیش‌فرض localhost
# در سرور production به دامنه‌ی واقعی تغییر دهید.
NEXT_JS_BASE_URL="${NEXT_JS_BASE_URL:-http://localhost:3003}"

echo "==> راه‌اندازی whatsapp-bridge"
echo "    ریشه‌ی پروژه: $ROOT"
echo "    پوشه‌ی bridge: $BRIDGE_DIR"
echo "    پورت bridge:  $BRIDGE_PORT"
echo "    Next.js URL:  $NEXT_JS_BASE_URL"
echo ""

# ─── ۱. بررسی وجود پوشه‌ی bridge ─────────────────────────────────────────────
if [ ! -f "$BRIDGE_DIR/package.json" ]; then
  echo "✗ خطا: پوشه‌ی mini-services/whatsapp-bridge پیدا نشد."
  echo "  مطمئن شوید فایل‌های پروژه به‌درستی روی سرور کپی شده‌اند."
  exit 1
fi

# ─── ۲. تولید secret تصادفی ─────────────────────────────────────────────────
SECRET="$(openssl rand -hex 32)"
echo "==> تولید secret تصادفی: ${SECRET:0:8}…${SECRET: -8} (۳۲ بایت)"

# ─── ۳. ساخت .env برای bridge ────────────────────────────────────────────────
ENV_BRIDGE="$BRIDGE_DIR/.env"
cat > "$ENV_BRIDGE" <<EOF
# Generated by deploy/setup-whatsapp-bridge.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do NOT commit this file — it contains the shared bridge secret.

WHATSAPP_BRIDGE_PORT=$BRIDGE_PORT
NEXT_JS_BASE_URL=$NEXT_JS_BASE_URL
WHATSAPP_BRIDGE_SECRET=$SECRET
LOG_LEVEL=info
EOF
echo "==> ساخته شد: $ENV_BRIDGE"

# ─── ۴. اضافه کردن به .env اصلی Next.js ──────────────────────────────────────
ENV_MAIN="$ROOT/.env"
touch "$ENV_MAIN"

# تابع کمکی: یک خط key=value را به .env اضافه می‌کند، فقط اگر key هنوز
# وجود نداشته باشد.
append_env() {
  local key="$1"
  local val="$2"
  local file="$3"
  if grep -q "^${key}=" "$file"; then
    echo "    ℹ $key از قبل در $file موجود است — رد شد"
  else
    echo "${key}=${val}" >> "$file"
    echo "    ✓ اضافه شد: $key به $file"
  fi
}

echo "==> به‌روزرسانی $ENV_MAIN"
append_env "WHATSAPP_BRIDGE_URL" "http://localhost:$BRIDGE_PORT" "$ENV_MAIN"
append_env "WHATSAPP_BRIDGE_SECRET" "$SECRET" "$ENV_MAIN"

# ─── ۵. نصب وابستگی‌های bridge ────────────────────────────────────────────────
echo "==> نصب وابستگی‌های bridge"
cd "$BRIDGE_DIR"
if command -v bun >/dev/null 2>&1; then
  echo "    استفاده از bun (پیشنهاد شده — سریع‌تر و بی‌مشکل با peer deps)"
  bun install
elif command -v npm >/dev/null 2>&1; then
  echo "    bun پیدا نشد — استفاده از npm --legacy-peer-deps"
  echo "    (پیشنهاد: bun را نصب کنید:  curl -fsSL https://bun.sh/install | bash)"
  # --legacy-peer-deps الزامی است چون Baileys peer deps سخت‌گیرانه دارد
  # و بدون این flag، npm با ERESOLVE خطا می‌دهد.
  # tsx به‌عنوان devDependency در package.json موجود است و بعد از نصب،
  # `npm run start` از آن استفاده می‌کند.
  npm install --legacy-peer-deps
else
  echo "✗ نه bun و نه npm پیدا نشد. یکی را نصب کنید:"
  echo "    curl -fsSL https://bun.sh/install | bash"
  exit 1
fi
cd "$ROOT"

# ─── ۶. ثبت bridge در pm2 ────────────────────────────────────────────────────
echo "==> ثبت سرویس‌ها در pm2"
# متغیر محیطی برای ecosystem.config.js (همان secret را می‌خواند)
export WHATSAPP_BRIDGE_SECRET="$SECRET"
export NEXT_JS_BASE_URL="$NEXT_JS_BASE_URL"
export WHATSAPP_BRIDGE_PORT="$BRIDGE_PORT"

if pm2 describe vignet-whatsapp-bridge >/dev/null 2>&1; then
  echo "    bridge از قبل در pm2 موجود است — restart (برای اعمال .env جدید)"
  # از restart استفاده می‌کنیم نه reload، چون bridge احتمالاً با config
  # قدیمی اجرا شده یا اصلاً اجرا نشده (خطای Script not found).
  pm2 restart vignet-whatsapp-bridge --update-env 2>/dev/null || pm2 reload deploy/ecosystem.config.js
else
  echo "    اولین ثبت bridge در pm2"
  pm2 start deploy/ecosystem.config.js
fi

pm2 save  # ذخیره برای استارت خودکار بعد از ریبوت

# ─── ۷. خلاصه ─────────────────────────────────────────────────────────────────
echo ""
echo "==> ✅ راه‌اندازی whatsapp-bridge کامل شد"
echo "    bridge با `npm run start` اجرا می‌شود (از tsx استفاده می‌کند)"
echo "    اگر bun نصب دارید، می‌توانید ecosystem.config.js را ویرایش کنید"
echo "    و args را به `run start:bun:prod` تغییر دهید."
echo ""
echo "وضعیت سرویس‌ها:"
pm2 status
echo ""
echo "لاگ‌های bridge را با این دستور ببینید:"
echo "  pm2 logs vignet-whatsapp-bridge"
echo ""
echo "برای تست: به داشبورد → Agents → Channels → WhatsApp → اتصال → «نمایش QR»"
echo "اگر باز هم خطای «سرویس واتساپ در حال اجرا نیست» گرفتید، لاگ bridge را"
echo "بررسی کنید:"
echo "  pm2 logs vignet-whatsapp-bridge --lines 50"
