import type { Solution } from '@/lib/marketing/solutions'

/** English equivalents for the public solution pages. Slugs stay stable so a
 * language switch never breaks inbound links or campaign URLs. */
export const SOLUTIONS_EN: Solution[] = [
  {
    slug: 'persian-ai-chatbot',
    metaTitle: 'Persian AI Chatbot for Websites and Social Channels | Vigent',
    metaDescription: 'Build a Persian AI chatbot grounded in your business data. Answer customers, recommend products, capture leads, and hand important conversations to your team.',
    keywords: ['Persian AI chatbot', 'Farsi chatbot', 'Persian customer support AI', 'AI chatbot for business', 'Persian website chatbot'],
    serviceType: 'Persian AI chatbot for sales and customer support',
    title: 'A Persian AI chatbot that understands your business',
    subtitle: 'More than a generic bot: it learns your products, policies, and brand voice, then helps customers across your website and messaging channels.',
    benefits: [
      { title: 'Natural Persian in your brand voice', desc: 'Choose a formal, balanced, or conversational style and fine-tune how the agent adapts to each customer.' },
      { title: 'Answers grounded in your data', desc: 'Add files, verified FAQs, and products so replies come from your actual business information.' },
      { title: 'Lead capture inside the conversation', desc: 'Collect a name, contact detail, and customer need so your team can follow up with context.' },
      { title: 'Smooth human handoff', desc: 'When a request needs human judgment, the agent transfers the conversation and its summary to your team.' },
    ],
    steps: [
      'Start with a ready-made sales, support, or lead-capture agent.',
      'Add your products, documents, and verified frequently asked questions.',
      'Test real scenarios, then connect the agent to your website or preferred channel.',
    ],
    faq: [
      { q: 'Which channels support the Persian chatbot?', a: 'You can use it on the website widget, a dedicated chat link, Telegram, WhatsApp, Instagram, Bale, and Rubika.' },
      { q: 'Can I customize how the agent speaks?', a: 'Yes. You can control personality, brand tone, formality, empathy, initiative, response rules, and fallback behavior.' },
      { q: 'What happens when the answer is not in my data?', a: 'The agent avoids inventing an answer, flags the conversation for follow-up, and keeps the unanswered question for knowledge review.' },
    ],
  },
  {
    slug: 'ecommerce-ai',
    metaTitle: 'AI for Ecommerce Sales and Customer Service | Vigent',
    metaDescription: 'Vigent reads current catalog and order data, recommends products, tracks orders, and helps shoppers buy across your website and messaging channels.',
    keywords: ['ecommerce AI assistant', 'AI shopping assistant', 'ecommerce chatbot', 'AI product recommendations', 'automated order tracking'],
    serviceType: 'AI sales assistant for ecommerce businesses',
    title: 'Ecommerce AI built to sell, not just chat',
    subtitle: 'Connect your catalog and orders to one sales assistant so customers get accurate, current answers wherever they contact you.',
    benefits: [
      { title: 'Recommendations based on real needs', desc: 'The agent asks about budget and requirements, finds suitable catalog items, and explains meaningful differences.' },
      { title: 'Current price and availability', desc: 'Replies use the Vigent catalog or synchronized WooCommerce data instead of stale information or guesses.' },
      { title: 'Order tracking without a phone call', desc: 'Customers can ask about their order in the same conversation and receive the relevant status.' },
      { title: 'One source across every sales channel', desc: 'The same product data powers conversations on your site, Instagram, Telegram, and WhatsApp.' },
    ],
    steps: [
      'Create an ecommerce agent from the recommended template.',
      'Import products or connect your WooCommerce store.',
      'Test a real shopping journey and activate your sales channels.',
    ],
    faq: [
      { q: 'Does Vigent connect to WooCommerce?', a: 'Yes. The official plugin synchronizes products, prices, stock, and the order information needed for customer replies.' },
      { q: 'Can I use it with a non-WordPress store?', a: 'Yes. Import products from CSV or manage them directly in the Vigent catalog.' },
      { q: 'Can customers see products inside the chat?', a: 'Yes. The agent can show a product card, price, description, and channel-appropriate action button.' },
    ],
  },
  {
    slug: 'customer-support-ai',
    metaTitle: 'AI Customer Support with Human Handoff | Vigent',
    metaDescription: 'Answer common questions instantly, manage conversations in one inbox, and hand sensitive cases to a human operator with full context.',
    keywords: ['AI customer support', 'customer support chatbot', 'unified customer inbox', 'human handoff AI', 'automated customer service'],
    serviceType: 'AI customer support and unified inbox',
    title: 'AI customer support, with a human whenever it matters',
    subtitle: 'Routine questions are resolved automatically, while sensitive requests reach your team with the conversation history intact.',
    benefits: [
      { title: 'Instant answers to repeat questions', desc: 'Business hours, service terms, order status, and guides are available without making customers wait.' },
      { title: 'A unified inbox', desc: 'Website and messaging conversations live in one place, so your team does not jump between tools.' },
      { title: 'Handoff with full context', desc: 'The operator sees the history and summary, then continues without asking the customer to repeat everything.' },
      { title: 'Improve answers from real conversations', desc: 'Unanswered questions are surfaced for review and can be added to the agent knowledge after approval.' },
    ],
    steps: [
      'Choose the recommended support agent and adjust its voice.',
      'Add verified guides, policies, and frequently asked questions.',
      'Connect channels and configure how your operators receive handoff alerts.',
    ],
    faq: [
      { q: 'Can an operator join an active conversation?', a: 'Yes. An operator can take ownership, complete the follow-up, and return future replies to the agent.' },
      { q: 'Can we see all conversations in one place?', a: 'Yes. Conversations from connected channels appear in the Vigent inbox alongside the customer profile.' },
      { q: 'Can some topics always go to a human?', a: 'Yes. Configure topics and phrases that should be marked immediately for human follow-up.' },
    ],
  },
  {
    slug: 'telegram',
    metaTitle: 'Telegram AI Chatbot for Sales and Support | Vigent',
    metaDescription: 'Launch a Telegram AI bot for customer replies, product guidance, order follow-up, and support grounded in your real business data.',
    keywords: ['Telegram AI bot', 'Telegram chatbot for business', 'Telegram sales bot', 'Telegram support automation', 'no-code Telegram bot'],
    serviceType: 'Telegram AI bot for sales and support',
    title: 'A Telegram AI chatbot for your business',
    subtitle: 'A Telegram bot that answers like your best teammate—using your business data, around the clock, in seconds.',
    benefits: [
      { title: 'Answers from your own data', desc: 'Add products, prices, and verified FAQs once; the agent answers from those sources instead of guessing.' },
      { title: 'Guided selling, not canned replies', desc: 'It discovers the customer need, recommends a suitable option, and supports the path to purchase.' },
      { title: 'Automated order follow-up', desc: 'A customer shares an order number and the agent reads the available delivery status from your store data.' },
      { title: 'Human handoff when needed', desc: 'When a conversation needs your team, the agent sends an alert with context and stops replying.' },
    ],
    steps: [
      'Create an agent in Vigent from a recommended template.',
      'Add products and business knowledge, or connect your WordPress store.',
      'Paste the Telegram bot token and run the connection test.',
    ],
    faq: [
      { q: 'Do I need to code a Telegram bot?', a: 'No. Get a bot token from BotFather, enter it in Vigent, and the connection is configured for you.' },
      { q: 'Does the agent understand Persian?', a: 'Yes. Vigent is optimized for natural Persian and also supports fully English agents and conversations.' },
      { q: 'What if the agent does not know an answer?', a: 'It says that the information needs review, offers a human path, and records the question for your knowledge review.' },
    ],
  },
  {
    slug: 'instagram',
    metaTitle: 'AI Auto-Reply for Instagram DMs | Vigent',
    metaDescription: 'Answer Instagram DMs quickly with AI grounded in your catalog: product guidance, accurate price and stock, lead capture, and human handoff.',
    keywords: ['Instagram DM automation', 'Instagram AI chatbot', 'Instagram auto reply', 'AI sales assistant Instagram', 'Instagram comment automation'],
    serviceType: 'AI replies and sales assistance for Instagram',
    title: 'AI-powered replies for Instagram DMs',
    subtitle: 'Never leave a serious inquiry waiting: Vigent answers price, availability, and product questions using your current business data.',
    benefits: [
      { title: 'Fast replies protect the sale', desc: 'The agent responds in seconds—even outside business hours—while customer intent is still high.' },
      { title: 'Accurate price and availability', desc: 'Instead of a generic “DM for price,” the agent reads the current catalog entry and shares the right item.' },
      { title: 'Turn followers into customers', desc: 'Guide the conversation toward an order or contact capture and keep qualified leads in the CRM.' },
      { title: 'One inbox across channels', desc: 'Instagram DMs sit beside Telegram, WhatsApp, and website chat with one customer history.' },
    ],
    steps: [
      'Create your agent and add the products it can discuss.',
      'Connect your eligible Instagram business account from Channels.',
      'Test the connection, then let the agent handle routine DMs and hand off exceptions.',
    ],
    faq: [
      { q: 'Is the Instagram connection secure?', a: 'The supported connection uses Meta APIs and Vigent never asks for or stores your Instagram password.' },
      { q: 'What happens with an unusual customer request?', a: 'The agent responds safely, gathers the minimum useful context, and hands the conversation to an operator.' },
      { q: 'Can I set the agent tone myself?', a: 'Yes. Configure personality, formality, empathy, initiative, must-do rules, and prohibited behavior.' },
    ],
  },
  {
    slug: 'whatsapp',
    metaTitle: 'WhatsApp AI Chatbot for Sales and Support | Vigent',
    metaDescription: 'Add an AI assistant to business WhatsApp for round-the-clock answers, sales guidance, order follow-up, human handoff, and unified CRM history.',
    keywords: ['WhatsApp AI chatbot', 'WhatsApp Business automation', 'WhatsApp sales bot', 'WhatsApp customer support', 'WhatsApp CRM'],
    serviceType: 'WhatsApp chatbot for sales, support, and CRM',
    title: 'An AI assistant for your business WhatsApp',
    subtitle: 'Meet customers where they already message you. Vigent responds accurately in your brand voice and keeps your team in control.',
    benefits: [
      { title: 'Available around the clock', desc: 'Customers receive a useful response in seconds without requiring a night-shift operator.' },
      { title: 'Natural multi-turn conversations', desc: 'The agent follows your brand voice, uses known customer context carefully, and avoids robotic repeated greetings.' },
      { title: 'Sales and follow-up together', desc: 'Recommend products, share verified prices, capture requests, and follow an order in the same thread.' },
      { title: 'Automatic CRM history', desc: 'Keep each WhatsApp contact and conversation history in the same customer profile used across channels.' },
    ],
    steps: [
      'Build the agent and add verified business information.',
      'Connect your business WhatsApp account from Channels.',
      'Run a real test, then let the agent handle routine messages while your team manages exceptions.',
    ],
    faq: [
      { q: 'Which WhatsApp account should I use?', a: 'Use a business account supported by the connection method shown in Channels. The setup guide walks through the required steps.' },
      { q: 'Can a teammate take over a conversation?', a: 'Yes. An operator can take ownership at any time; the AI stops replying until the conversation is returned.' },
      { q: 'How is usage charged?', a: 'Your trial includes initial reply credit. Fixed Instagram automations remain free, and AI credit is deducted only after a successful generated reply.' },
    ],
  },
  {
    slug: 'woocommerce',
    metaTitle: 'WooCommerce AI Chatbot and Sales Assistant | Vigent',
    metaDescription: 'Connect WooCommerce to an AI sales assistant that can use synchronized products, stock, content, and order status across your customer channels.',
    keywords: ['WooCommerce AI chatbot', 'WooCommerce sales assistant', 'WordPress AI chatbot', 'WooCommerce order tracking bot', 'WooCommerce customer support'],
    serviceType: 'AI sales and support assistant for WooCommerce',
    title: 'An AI sales assistant for your WooCommerce store',
    subtitle: 'Install the plugin, synchronize your store, and answer customers from current product and stock data on your site and messaging channels.',
    benefits: [
      { title: 'Automatic sync through the official plugin', desc: 'Product and order changes reach Vigent without repetitive manual imports.' },
      { title: 'Accurate price and stock replies', desc: 'The agent uses the latest synchronized store data instead of outdated values or guesses.' },
      { title: 'Order tracking without support calls', desc: 'Customers can share an order number and receive the available fulfillment status from WooCommerce.' },
      { title: 'Your site content becomes useful knowledge', desc: 'Selected WordPress posts and pages can support answers from your own guides and articles.' },
    ],
    steps: [
      'Create the agent you want to connect in Vigent.',
      'Install the Vigent plugin in WordPress and enter the generated webhook details.',
      'Run a full synchronization, then verify products, orders, and selected content in the agent.',
    ],
    faq: [
      { q: 'Will the plugin slow down my site?', a: 'The integration is designed to send small requests when relevant store data changes instead of doing heavy work on customer page loads.' },
      { q: 'Can I use the plugin without WooCommerce?', a: 'Yes. On a WordPress-only site, selected posts and pages can still be sent to the agent knowledge base.' },
      { q: 'How is the store connection protected?', a: 'Webhook requests are authenticated with an HMAC-SHA256 signature and sensitive stored credentials are encrypted.' },
    ],
  },
]
